const DEFAULT_WORDS_COUNT = 200;
const COUNT_DOWN_60 = 60;
const COUNT_DOWN_30 = 30;
const COUNT_DOWN_15 = 15;
const DEFAULT_COUNT_DOWN = COUNT_DOWN_60;

export {
DEFAULT_WORDS_COUNT,
DEFAULT_COUNT_DOWN,
COUNT_DOWN_60,
COUNT_DOWN_30,
COUNT_DOWN_15
}